import {useMemo,type ReactNode} from 'react'; import {ThemeProvider,CssBaseline} from '@mui/material'; import {theme} from '../theme/theme'; import {LearningSessionProvider} from '../state/LearningSessionProvider'; import {AiHybridEducationCenterAdapter} from '../adapters/ai-hybrid/AiHybridEducationCenterAdapter'; import {PdfJsLocalDocumentAdapter} from '../adapters/pdfjs/PdfJsLocalDocumentAdapter'; import {BrowserSpeechAdapter} from '../adapters/speech/BrowserSpeechAdapter'; import {UnavailableHostCommitAdapter} from '../adapters/local-demo/UnavailableHostCommitAdapter'; import {RealHostCommitAdapter} from '../adapters/host-bff/RealHostCommitAdapter'; import {TesseractLocalOcrAdapter} from '../adapters/tesseract/TesseractLocalOcrAdapter'; import {loadHostConfig} from '../services/hostRuntimeConfig'; import {OpenMAICAdapter} from '../adapters/openmaic/OpenMAICAdapter'; import {useSyncExternalStore} from 'react';
/* host-config 变化通知：DataControlPage 保存配置后触发重装配 */
let hostConfigListeners:(()=>void)[]=[];let configSnapshot=0;
export function notifyHostConfigChanged():void{configSnapshot+=1;hostConfigListeners.forEach((l)=>l());}
export function notifyOpenmaicConfigChanged():void{configSnapshot+=1;hostConfigListeners.forEach((l)=>l());}
function useHostConfigVersion():number{return useSyncExternalStore((onStoreChange)=>{hostConfigListeners.push(onStoreChange);return()=>{hostConfigListeners=hostConfigListeners.filter((l)=>l!==onStoreChange);};},()=>configSnapshot,()=>configSnapshot);}
/* 供展示组件（ModeBanner 等）订阅运行时配置变化：AppProviders 重渲染会因 children 引用稳定被子树跳过，组件必须自己订阅 */
export function useRuntimeConfigVersion():number{return useHostConfigVersion();}
export function AppProviders({children}:{children:ReactNode}):JSX.Element{/* AI 开关是运行时配置（数据控制页可改），常驻混合适配器；关闭时 routeLearningIntent/gradeQuiz 直接返回 local-demo 结果，行为与旧装配完全一致 *//* 宿主提交端口：host-config 启用且 BFF 可用时装 RealHostCommitAdapter，否则 Unavailable（候选不提交） */const hostConfigVersion=useHostConfigVersion();const deps=useMemo(()=>{const hostConfig=loadHostConfig();const aiHybrid=new AiHybridEducationCenterAdapter();return{education:new OpenMAICAdapter(aiHybrid),documents:new PdfJsLocalDocumentAdapter(),speech:new BrowserSpeechAdapter(),host:hostConfig.enabled?new RealHostCommitAdapter():new UnavailableHostCommitAdapter() as import('../adapters/ports/HostCommitPort').HostCommitPort,ocr:new TesseractLocalOcrAdapter()};},[hostConfigVersion]);return<ThemeProvider theme={theme}><CssBaseline/><LearningSessionProvider {...deps}>{children}</LearningSessionProvider></ThemeProvider>}
